---
- hosts: all
  become: true
  tasks:

  - name: update repository
    apt:
      update_cache: yes
      state: latest
  
  - name: install apache2 package
    apt:
      name: apache2
  - name: add php support
    apt:
      name: libapache2-mod-php
      state: latest
