---
 - hosts: all
   become: true
   pre_tasks:

   - name: install updates
     tags: always
     dnf:
       update_only: yes
       update_cache: yes
     when: ansible_distribution == "CentOS"

   - name: install updates (Ubuntu
     tags: always)
     apt:
       upgrade: dist
       update_cache: yes
     when: ansible_distribution == "UbuntU"

 - hosts: workstations
   become: true
   tasks:

     - name: install upzip
       tags: unzip,workstation,pc
       package:
         name: unzip

     - name: install terraform
       tags: terraform,workstation
       unarchive:
         src: https://releases.hashicorp.com/terraform/1.9.4/terraform_1.9.4_linux_amd64.zip
         dest: /usr/local/bin
         remote_src: yes
         mode: 0755
         owner: root
         group: root
           

 - hosts: web_servers
   become: true
   tasks:

   - name: install apache and php for Ubuntu servers
     tags: apache,apache2,ubuntu
     apt:
       name:
         - apache2
         - libapache2-mod-php
       state: latest
     when: ansible_distribution == "Ubuntu"

   - name: copy default html file
     tags: new,siteupload,apache,apache2
     copy:
       src: default_site.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644
 
   - name: install apache and php for CentOS servers
     tags: centos,apache,httpd
     dnf:
       name:
         - httpd
         - php
       state: latest
     when: ansible_distribution == "CentOS"

